name: Update RCE

on:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hourly RCE fetcher
        run: python update_rce.py

      - name: Commit and push if changed
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add rce.json rce_changes.txt || true
          if ! git diff --staged --quiet; then
            git commit -m "Update RCE hourly data"
            git push
          else
            echo 'No changes to commit'
          fi
